# Use the latest version of Ubuntu as the base image
FROM ubuntu:latest

# Update APT package list and upgrade all packages
RUN apt-get update && apt-get upgrade -y

# Define the command to run when the container starts
CMD echo "Hello, World!"
